cluster.name: "elasticsearch"
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.unicast.hosts: ["172.16.11.119:9200","172.16.11.119:9021"]
xpack.monitoring.collection.enabled: true

#network.host: 0.0.0.0
#transport.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# # set to 1 to allow single node clusters
# # Details: https://github.com/elastic/elasticsearch/pull/17288
# xpack.license.self_generated.type: trial
# xpack.security.enabled: true
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.verification_mode: certificate
# xpack.security.http.ssl.key:  certs/elasticsearch/elasticsearch.key
# xpack.security.http.ssl.certificate: certs/elasticsearch/elasticsearch.crt
# xpack.security.http.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
#
# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.key:  certs/elasticsearch/elasticsearch.key
# xpack.security.transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
# xpack.security.transport.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
