#============================ xpack monitor ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["172.16.16.10:9200","172.16.16.10:9201"]

#=========================== Filebeat inputs =============================
filebeat.inputs:
#test
- type: log
  enabled: true
  paths:
    - /path/to/log/*.log
  fields:
    log_topics: test
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}'
    negate: true
    match: after
    max_lines: 1000
    timeout: 30s
#============================ kafka output ===============================
output.kafka:
  enabled: true
  hosts: ["172.16.16.10:9092","172.16.16.10:9093","172.16.16.10:9094"]
  worker: 5
  
  topic: '%{[fields][log_topics]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
