http.host: 0.0.0.0
# read password from logstash.keystore
# xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: http://172.16.16.10:9200
