version: '3.6'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.3.1
    container_name: filebeat
    command: --strict.perms=false -e
    user: root
    volumes:
      - /etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /etc/logs:/home/logs
    networks: ['stack']
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5

networks: {stack: {}}
